### ISSUE TITLE
Branch for APS 2.x support issue: integration test fails due to Mockito or SpringBoot

### ISSUE THREAD

**Issue by OpenPj** [OpenPj/alfresco-process-services-project-sdk#14]
Trying to execute integration tests returns the following error:
`Caused by: java.lang.NoClassDefFoundError: org/mockito/codegen/EmailTemplateService$MockitoMock$22412768
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:554)
	... 226 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.mockito.codegen.EmailTemplateService$MockitoMock$22412768
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 233 common frames omitted`

It seems that the upgrade of SpringBoot 2 included in APS 2.x is braking something with Junit and Mockito.
Need more investigation...

**Comment by OpenPj** [comment]
Issue resolved with the following components:

- a new Swagger client module for generating APS client from Open API
- a new Integration Tests module containing Java classes with tests using the generated swagger client
